/****** Object:  Database [FAIVE_CAPSTONE]    Script Date: 2023-10-24 9:52:28 AM ******/
CREATE DATABASE [FAIVE_CAPSTONE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FAIVE_CAPSTONE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FAIVE_CAPSTONE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FAIVE_CAPSTONE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FAIVE_CAPSTONE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FAIVE_CAPSTONE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ARITHABORT OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET  MULTI_USER 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET QUERY_STORE = ON
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [FAIVE_CAPSTONE] SET  READ_WRITE 
GO

USE [FAIVE_CAPSTONE]
GO

/****** Object:  Table [dbo].[Candidate]    Script Date: 2023-10-24 9:47:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Candidate](
	[ID] [int] IDENTITY(100001,1) NOT NULL,
	[CandidateName] [varchar](40) NOT NULL,
	[EmailID] [varchar](40) NOT NULL,
	[PersonalityScore] [int] NULL,
	[AptitudeScore] [int] NULL,
	[LoginPassword] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[EmailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--DROP TABLE Candidate

/****** Object:  Table [dbo].[HRExecutive]    Script Date: 2023-10-24 9:48:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HRExecutive](
	[ID] [int] IDENTITY(900001,1) NOT NULL,
	[HRName] [varchar](40) NOT NULL,
	[EmailID] [varchar](40) NOT NULL,
	[LoginPassword] [varchar](40) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[EmailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--DROP TABLE HRExecutive

/****** Object:  Table [dbo].[JobPosting]    Script Date: 2023-10-24 9:49:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JobPosting](
	[ID] [int] IDENTITY(500001,1) NOT NULL,
	[HRID] [int] NULL,
	[Title] [varchar](40) NOT NULL,
	[JobLocation] [varchar](40) NULL,
	[PostedDate] [date] NOT NULL,
	[LastDate] [date] NOT NULL,
	[Wages] [int] NULL,
	[Skills] [varchar](1) NULL,
	[Personality] [varchar](1) NULL,
	[Education] [varchar](1) NULL,
	[Experience] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JobPosting]  WITH CHECK ADD FOREIGN KEY([HRID])
REFERENCES [dbo].[HRExecutive] ([ID])
GO

--DROP TABLE JobPosting

/****** Object:  Table [dbo].[JobCandidate]    Script Date: 2023-10-24 9:49:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JobCandidate](
	[JobID] [int] NULL,
	[CandidateID] [int] NULL,
	[FitmentRank] [int] NULL,
	[MatchPercent] [decimal](3, 2) NULL,
	[CandidateStatus] [varchar](1) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JobCandidate]  WITH CHECK ADD FOREIGN KEY([CandidateID])
REFERENCES [dbo].[Candidate] ([ID])
GO

ALTER TABLE [dbo].[JobCandidate]  WITH CHECK ADD FOREIGN KEY([JobID])
REFERENCES [dbo].[JobPosting] ([ID])
GO

--DROP TABLE JobCandidate

/****** Object:  Table [dbo].[CandidateResume]    Script Date: 2023-10-24 9:51:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CandidateResume](
	[CandidateID] [int] NULL,
	[Skills] [varchar](1) NULL,
	[Personality] [varchar](1) NULL,
	[Education] [varchar](1) NULL,
	[Experience] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CandidateResume]  WITH CHECK ADD FOREIGN KEY([CandidateID])
REFERENCES [dbo].[Candidate] ([ID])
GO

--DROP TABLE CandidateResume